openweb:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 167.172.5.48
      user: openweb_dp
      password: 84c3b8fb990eba2a1b338669b3f03b0155e6b329
      port: 51123
      dbname: dp_mediagrid
      schema: public
