silverpush:
  target: dev
  outputs:
    dev:
      type: postgres
      host: m-db.ccsqbljgvpi4.ap-south-1.rds.amazonaws.com
      user: tayyab
      password: vI2nX5uV6mK4kp9aJ9xV7oF3gZ2bV0
      port: 28463
      dbname: mirror
      schema: public
